

# H2 in memory configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver



# 2. Impostazioni JPA/Hibernate specifiche per H2
# 'create-drop' crea lo schema all'inizio dei test e lo distrugge alla fine.
spring.jpa.hibernate.ddl-auto=update


#H2 console abilitation
spring.h2.console.enabled=false 

#Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


spring.liquibase.enabled=true