INSERT INTO db_news.category (name, category_code, created_at, modified_at, deleted_at, id, category_id) VALUES('', '', CURRENT_TIMESTAMP, '', '', 0, 0);
INSERT INTO db_news.comment (`text`, positive_vote, negative_vote, user_id, review_id, news_id, created_at, modified_at, deleted_at, comment_id, comment_code, `date`, preview_id) VALUES('', 0, 0, 0, 0, 0, CURRENT_TIMESTAMP, '', '', 0, '', CURRENT_TIMESTAMP, 0);
INSERT INTO db_news.contest (name, `desc`, contest_code, created_at, modified_at, deleted_at, image_id) VALUES('', '', '', CURRENT_TIMESTAMP, '', '', 0);
INSERT INTO db_news.employee (employee_code, created_at, modified_at, deleted_at, name, surname, email, password) VALUES('', CURRENT_TIMESTAMP, '', '', '', '', '', '');
INSERT INTO db_news.image (content, `desc`, image_code, created_at, modified_at, deleted_at, name) VALUES(?, '', '', CURRENT_TIMESTAMP, '', '', '');
INSERT INTO db_news.image_category (image_id, category_id, created_at, modified_at, deleted_at) VALUES(0, 0, CURRENT_TIMESTAMP, '', '');
INSERT INTO db_news.news (news_code, `date`, positive_vote, negative_vote, category_id, created_at, modified_at, deleted_at, image_id, title, summary, employee_id) VALUES('', CURRENT_TIMESTAMP, 0, 0, 0, CURRENT_TIMESTAMP, '', '', 0, '', '', 0);
INSERT INTO db_news.news_tag (news_id, tag_id, created_at, news_tag_code) VALUES(0, 0, CURRENT_TIMESTAMP, '');
INSERT INTO db_news.news_text (`text`, order_num, news_text_code, news_id, created_at, modified_at, deleted_at, `type`, image_id) VALUES('', 0, '', 0, CURRENT_TIMESTAMP, '', '', '', 0);
INSERT INTO db_news.preview (title, summary, `date`, category_id, employee_id, created_at, modified_at, deleted_at, preview_code, positive_vote, negative_vote) VALUES('', '', CURRENT_TIMESTAMP, 0, 0, CURRENT_TIMESTAMP, '', '', '', 0, 0);
INSERT INTO db_news.preview_tag (preview_id, tag_id, created_at, preview_tag_code) VALUES(0, 0, CURRENT_TIMESTAMP, '');
INSERT INTO db_news.preview_text (`text`, `type`, order_num, preview_text_code, preview_id, image_id, created_at, modified_at, deleted_at) VALUES('', '', 0, '', 0, 0, CURRENT_TIMESTAMP, '', '');
INSERT INTO db_news.prize_article (name, `desc`, prize_article_code, created_at, modified_at, deleted_at) VALUES('', '', '', CURRENT_TIMESTAMP, '', '');
INSERT INTO db_news.prize_article_contest (prize_article_id, contest_id, created_at, modified_at, deleted_at, prize_article_contest_code) VALUES(0, 0, CURRENT_TIMESTAMP, '', '', '');
INSERT INTO db_news.review (review_code, `date`, positive_vote, negative_vote, category_id, created_at, modified_at, deleted_at, vote, image_id, employee_id, title, summary) VALUES('', CURRENT_TIMESTAMP, 0, 0, 0, CURRENT_TIMESTAMP, '', '', 0, 0, 0, '', '');
INSERT INTO db_news.review_tag (review_id, tag_id, created_at, review_tag_code) VALUES(0, 0, CURRENT_TIMESTAMP, '');
INSERT INTO db_news.review_text (`text`, `type`, order_num, review_text_code, review_id, created_at, modified_at, deleted_at, image_id) VALUES('', '', 0, '', 0, CURRENT_TIMESTAMP, '', '', 0);
INSERT INTO db_news.tag (name, tag_code, created_at, modified_at, deleted_at, category_id) VALUES('', '', CURRENT_TIMESTAMP, '', '', 0);
INSERT INTO db_news.`user` (user_code, created_at, modified_at, deleted_at, name, surname, username, password, email) VALUES('', CURRENT_TIMESTAMP, '', '', '', '', '', '', '');
INSERT INTO db_news.user_tag (user_id, tag_id, created_at, user_tag_code, modified_at, deleted_at) VALUES(0, 0, CURRENT_TIMESTAMP, '', '', '');